language: android
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - android-21
    - add-on
    - extra
    - platform-tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-21


env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2

sudo: required

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s "768x1280"
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew :app:build



notifications:
  email:
    recipients:
    - bra.patrik@gmail.com
    on_failure: always
    on_success: always